{{- range $h, $cluster := .Values.clusters }}
#
# Cluster {{ $cluster }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kad-cluster-leaf-{{ $cluster }}
  namespace: argo
  labels:
    cluster: {{ $cluster }}
    app: kad-cluster
spec:
  project: {{ $.Values.project }}
  source:
    repoURL: {{ $.Values.repoURL }}
    targetRevision: HEAD
    path: app_v8
  destination:
    name: {{ $cluster }}
    namespace: kad
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true 
{{- end }}
