---
# htaccess file with demo credentials
apiVersion: v1
kind: Secret
metadata:
  name: htaccess
  namespace: kube-system
data:
  ht: ZGF0YXNjcmlwdDokYXByMSRxdndVQ3VVbCRPdmVKbFkzZnptMTkxY25zRTl1WDIxCg==
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kubernetes-dashboard
  namespace: kube-system
  annotations:
    traefik.frontend.rule.type: PathPrefixStrip
    ingress.kubernetes.io/auth-type: "basic"
    ingress.kubernetes.io/auth-secret: "htaccess"
spec:
  rules:
  - http:
      paths:
      - path: /kubeconfig/
        backend:
          serviceName: kubeconfig-exposer
          servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: kubeconfig-exposer
  namespace: kube-system
spec:
  selector:
    app: kubeconfig-exposer
  ports:
  - protocol: TCP
    port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeconfig-exposer
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubeconfig-exposer
  template:
    metadata:
      labels:
        app: kubeconfig-exposer
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config
          mountPath: /usr/share/nginx/html/
      volumes:
      - name: config
        hostPath:
          path: /etc/kubernetes/users/
          type: Directory

