---
apiVersion: v1
kind: Service
metadata:
  name: kad
  namespace: kadsingle
spec:
  selector:
    app: kad
  ports:
  - name: web
    protocol: TCP
    port: 80
    targetPort: 5000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kad
  namespace: kadsingle
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kad
    spec:
      containers:
      - name: app
        image: tomkukral/kad
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: REDIS_SERVER
          value: localhost:6379
        - name: COLOR
          valueFrom:
            configMapKeyRef:
              name: kad
              key: option.color
        volumeMounts:
        # file will be /etc/kad/config.conf
        - name: config
          mountPath: /etc/kad/
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
      volumes:
      - name: config
        configMap:
          name: kad
          items:
          - key: config.yml
            path: config.conf
