---
apiVersion: v1
kind: Service
metadata:
 name: kad
spec:
  selector:
    app: kad
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kad
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kad
    spec:
      containers:
      - name: app
        image: tomkukral/kad
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
          - name: REDIS_SERVER
            value: localhost
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
#        volumeMounts:
#          - mountPath: "/data"
#            name: redis-storage-volume
#      volumes:
#        - name: redis-storage-volume
#          emptyDir: {}
