apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: redis-disk
  annotations:
    volume.beta.kubernetes.io/mount-options: "discard"
spec:
  capacity:
    storage: "1Gi"
  accessModes:
    - "ReadWriteOnce"
  gcePersistentDisk:
    fsType: "ext4"
    pdName: "redis-disk"
