apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  creationTimestamp: 2018-11-01T10:40:58Z
  name: kad
  namespace: kad
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kad
  targetCPUUtilizationPercentage: 50
