---
# htaccess file with demo credentials
apiVersion: v1
kind: Secret
metadata:
  name: htaccess
  namespace: prometheus
data:
  ht: ZGF0YXNjcmlwdDokYXByMSRxdndVQ3VVbCRPdmVKbFkzZnptMTkxY25zRTl1WDIxCg==
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: basicauth
  namespace: prometheus
spec:
  basicAuth:
    secret: htaccess
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus
  namespace: prometheus
spec:
  entryPoints:
    - http
    - https
  routes:
  - match: HostRegexp(`prometheus.{domain:.+}`)
    kind: Rule
    middlewares:
    - name: basicauth
    services:
    - name: prometheus
      port: 9090
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
  namespace: prometheus
spec:
  entryPoints:
    - http
    - https
  routes:
  - match: HostRegexp(`grafana.{domain:.+}`)
    kind: Rule
    middlewares:
    - name: basicauth
    services:
    - name: grafana
      port: 80
