namespace: prometheus
resources:
- namespace.yml
- rbac.yml
- pvc.yml
- ingress.yml
- svc.yml
- be-deploy.yml
- be-svc.yml
- kube-state-metrics.yml
- prometheus.yml
- alertmanager.yml
- grafana.yml
- karma.yml
- node-exporter-ds.yml
- telegram-bot-sealed.yml
- telegram-bot.yml

configMapGenerator:
- name: prometheus-config
  files:
  - prometheus.yml=prometheus-config.yml
- name: prometheus-rules
  files:
  #- rules/etcd.yml
  #- rules/kube-state-metrics.yml
  - rules/node-exporter.yml
  - rules/prometheus.yml
- name: grafana-config
  files:
  - grafana.ini=grafana-config.ini
  - datasources.yml=grafana-datasources.yml
  - dashboards.yml=grafana-dashboards.yml
- name: karma-config
  files:
  - config.yml=karma-config.yml
- name: alertmanager-config
  files:
  - config.yml=alertmanager-config.yml
- name: grafana-dashboards
  files:
  - 1860.json=grafana-dashboard-1860-min.json
  #- rendered/dashboards/apiserver.json
  #- rendered/dashboards/cluster-total.json
  #- rendered/dashboards/controller-manager.json
  #- rendered/dashboards/k8s-resources-cluster.json
  #- rendered/dashboards/k8s-resources-namespace.json
  #- rendered/dashboards/k8s-resources-node.json
  #- rendered/dashboards/k8s-resources-pod.json
  #- rendered/dashboards/k8s-resources-workload.json
  #- rendered/dashboards/k8s-resources-workloads-namespace.json
  #- rendered/dashboards/kubelet.json
  #- rendered/dashboards/namespace-by-pod.json
  #- rendered/dashboards/namespace-by-workload.json
  #- rendered/dashboards/persistentvolumesusage.json
  #- rendered/dashboards/pod-total.json
  #- rendered/dashboards/proxy.json
  #- rendered/dashboards/scheduler.json
  #- rendered/dashboards/statefulset.json
  #- rendered/dashboards/workload-total.json
generatorOptions:
  disableNameSuffixHash: false
  labels:
    generator: kustomize
#images:
#- name: karma
#  newTag: v0.78
