namespace: prometheus
resources:
- namespace.yml
- rbac.yml
- svc.yml
- pvc.yml
- be-deploy.yml
- be-svc.yml
- prometheus.yml
- alertmanager.yml
- grafana.yml
- karma.yml
- ingress.yml
- node-exporter-ds.yml

configMapGenerator:
- name: prometheus-config
  files:
  - prometheus.yml=prometheus-config.yml
- name: prometheus-rules
  files:
  #- rules/etcd.yml
  #- rules/kube-state-metrics.yml
  - rules/node-exporter.yml
  - rules/prometheus.yml
- name: grafana-config
  files:
  - grafana.ini=grafana-config.ini
  - datasources.yml=grafana-datasources.yml
  - dashboards.yml=grafana-dashboards.yml
- name: karma-config
  files:
  - config.yml=karma-config.yml
- name: alertmanager-config
  files:
  - config.yml=alertmanager-config.yml
- name: grafana-dashboards
  files:
  - 1860.json=grafana-dashboard-1860-min.json
generatorOptions:
  disableNameSuffixHash: false
  labels:
    generator: kustomize
#images:
#- name: karma
#  newTag: v0.78
