apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: telegram-bot
  namespace: prometheus
spec:
  encryptedData:
    admin: AgAZKnRbXgkQNyQ0OQ83gLpWTT497L6zqEDaI7vg6tGHIugyV3fIA7JOhdlm+xMiNPHNy25SlokMjaGAocIh3cEpM1AeuAtEm/LLseCoTS5Ayrnhw8oQCGe7JVt+nukw6hnwyrRZX70tJXji2eExO4sU3cRaAio2PHmhVgl4LD/ziafv4U/WL3E9vV5nyGgFzHLwCuR9hnOHQ6atuFako/IvSfJiQbN9obDONvS8IAMooZJy9bOTWyWlD2w7m9zGJ9NsOOSYZ3O72tI+tPVAf4pfPju2hKDqZ/lFJqGlHhfzmzcfEEpLrfxNEKww+ASJ44zjCuK68/m/6HiQ1CbdeinazG+qevWxufRbE3di74aTomAiVB3j1+m2I+eIUslBhYNzk20kJvJtUy6hu8yb80IJyO4F1ugp7kQ85T3quFxkZ9VrskL+zvfSUsq340rijvbAxE7wYTfTNrit/jve8XvfIvAkQbmXZLokDYX8zMJTKQREjEm6E2tCqfT9UetGfx2NS8KkVvVXdH4vbK2RJPtW6zVwTip3ZKbd1J+YUEDxDhH0n+e0Hqd/FxWcXUgYB4tyxaBwTrjweS1I22lbFUmD7IhisDYuQY4Q+9b0qsDT5/Dx2iznGpCtmZgYXMgtBDIhQknLfTWabZYF11QgJ16ymXthU2612xbiSx/TVrgkThSxqjnF6wo4MXGk7o0MqWdC6HvQcrY4HvQ=
    token: AgBWPaq9honypZaX4VLn1hBKgWpWKmdEL777B5vxP2gpQr5q5G/oA27dfIoG7BNz86iMtwjS9VzaHzAgOYiziOKcGdWpHloybcKW1LbPHfCU/abYxfJgHcxv7prvfofMnYdtwsVRZzLlZMoFMs+F+nhNn5P7kpKnS+2Uuhp5ldGk9j5+ZbHg3YCnfl7JRj6gmHUNSxCbc9Uacw7E5QbwzBeETvo+AbqOCxQi/IHcKM/MrGhYg9RBTCxUuecJSkjtqorVyHYDv1HBjhVr/7a6q1R1j83ACQtchc38s98J3TcOmjrWaz+DJNfKnsRDqJ/k0sL3tqXbvKle9W4dSh4rNE57JqMe7vEDb+R0oUEA5rGLqKUHsY3lSX3AWuhdEXJzNYeU8zx4mnZidd3MC0nbfuO064uSkD1bKomlRVz+t9Mohk34LCxVwNGV2INXQba0OAAOB5ISeOSqZ1m8Hk0S9HJFNXhpTlXCWDngjzGTjQ9vzIeFF8wuAe6cbuNNWVYGmgOxon0q7DsCjADuclcLRyGiLCVtdzdfVOFBKju6qc/NZvB/MIuXbJygbjegvErcoQJNSx2pVkzh/TGyRmHRorHs9tVP8bmiombGqle0cdurNxZ5pA3+ExN7d5XSEXFAQ6Q/qBFwiWu2OIot7U/xwTKTTMpYQRVo8V1xJLKhxzF9dAXZmmgb2WSegmAbVty4oa72XSRbHNyztHlCLxCmvR/6jff88oNehtW7vjGIoRDR/aFKAgi8Wj1Sxm9K204=
  template:
    metadata:
      creationTimestamp: null
      name: telegram-bot
      namespace: prometheus

