apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tomkukral/kubernetes-examples
    targetRevision: HEAD
    path: argocd
  destination:
    server: https://api.c0.k8s.6shore.net:6443
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true # Namespace Auto-Creation ensures th
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
spec:
  project: default
  source:
    repoURL: https://github.com/tomkukral/kubernetes-examples
    targetRevision: HEAD
    path: nginx
  destination:
    server: https://api.c0.k8s.6shore.net:6443
    namespace: default
