apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: argocd-server
  namespace: argocd
  annotations:
    traefik.frontend.rule.type: PathPrefixStrip
    traefik.ingress.kubernetes.io/preserve-host: "true"
spec:
  rules:
  - host: argo.c0.k8s.6shore.net
    http:
      paths:
      - path: /
        backend:
          serviceName: argocd-server
          servicePort: 80
