namespace: argocd
resources:
- namespace.yml
- deploy.yml
- ingress.yml
- project-default.yml
patchesStrategicMerge:
- patch_server.yml
configMapGenerator:
- name: argocd-gpg-keys-cm
  behavior: merge
  files:
  - 27AEE1EDDF7F3E5D
- name: argocd-cm
  behavior: merge
  files:
  - repositories
secretGenerator:
- name: argocd-secret
  behavior: merge
  literals:
  # workshopSD
  - admin.password=$2y$10$UwZ84ZgbjPxY3z6C4G8rt.MGZAwKCeugQf0ofkxDVeBlTVqn0lxzO
  files:
  - repositories
