apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kad
  namespace: argo
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  project: default
  source:
    helm:
      values: |
        replicas: 2
        clusters:
        - c0
    path: kad-cluster
    targetRevision: HEAD
    repoURL: https://github.com/tomkukral/kubernetes-examples
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
