---
apiVersion: v1
kind: Service
metadata:
  name: kad
  namespace: kad
spec:
  selector:
    app: kad
  ports:
    - protocol: TCP
      targetPort: 5000
      port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: kad
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kad
  namespace: kad
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kad
    spec:
      containers:
      - name: app
        image: tomkukral/kad
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
          - name: REDIS_SERVER
            #value: redis-0.redis
            value: redis-0.redis.kad.svc.cluster.local:6379
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: kad
spec:
  selector:
    matchLabels:
      app: redis
  serviceName: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
        volumeMounts:
          - mountPath: "/data"
            name: redis-disk
  volumeClaimTemplates:
  - metadata:
      name: redis-disk
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
