---
apiVersion: v1
kind: Service
metadata:
  name: kad
  namespace: kad
spec:
  selector:
    app: kad
  ports:
    - protocol: TCP
      targetPort: 5000
      port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: kad
spec:
  selector:
    app: redis
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 6379
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kad
  namespace: kad
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: kad
    spec:
      containers:
      - name: nginx
        image: tomkukral/kad
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
          - name: REDIS_SERVER
            value: redis:6379
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
  namespace: kad
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
        volumeMounts:
          - mountPath: "/data"
            name: redis-storage-volume
      volumes:
        - name: redis-storage-volume
          persistentVolumeClaim:
            claimName: redis-disk
