{{- range $h, $cluster := .Values.clusters }}
#
# Cluster {{ $cluster }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-{{ $cluster }}
  namespace: argocd
  labels:
    initial: "yes"
    cluster: {{ $cluster }}
    app: traefik
spec:
  project: {{ $.Values.project }}
  source:
    repoURL: {{ $.Values.repoURL }}
    targetRevision: HEAD
    path: traefik
  destination:
    name: {{ $cluster }}
    namespace: traefik
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-{{ $cluster }}
  namespace: argocd
  labels:
    initial: "yes"
    cluster: {{ $cluster }}
    app: nginx
spec:
  project: {{ $.Values.project }}
  source:
    repoURL: {{ $.Values.repoURL }}
    targetRevision: HEAD
    path: nginx
  destination:
    name: {{ $cluster }}
    namespace: default
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server-{{ . }}
  namespace: argocd
  labels:
    initial: "yes"
    cluster: {{ $cluster }}
    app: metrics-server
spec:
  project: {{ $.Values.project }}
  source:
    repoURL: {{ $.Values.repoURL }}
    targetRevision: HEAD
    path: metrics-server
  destination:
    name: {{ $cluster }}
    namespace: kube-system
---

{{ range $n, $i := $.Values.kadApps }}
# kad {{ $cluster }}-{{ $i }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kad-v{{ $i }}-{{ $cluster }}
  namespace: argocd
  labels:
    cluster: {{ $cluster }}
    app: kad
    kad/version: "{{ $i }}"
spec:
  project: {{ $.Values.project }}
  source:
    repoURL: {{ $.Values.repoURL }}
    targetRevision: HEAD
    path: app_v{{ $i }}
  destination:
    name: {{ $cluster }}
    namespace: kad
---
{{ end }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kad-ingress-{{ . }}
  namespace: argocd
  labels:
    cluster: {{ $cluster }}
    app: kad-ingress
spec:
  project: {{ $.Values.project }}
  source:
    repoURL: {{ $.Values.repoURL }}
    targetRevision: HEAD
    path: ingress
  destination:
    name: {{ $cluster }}
    namespace: kad
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-{{ $cluster }}
  namespace: argocd
  labels:
    cluster: {{ $cluster }}
    app: prometheus
spec:
  project: {{ $.Values.project }}
  source:
    repoURL: {{ $.Values.repoURL }}
    targetRevision: HEAD
    path: prometheus
  destination:
    name: {{ $cluster }}
    namespace: prometheus
{{- end }}
