{{- range $h, $cluster := .Values.clusters }}
#
# Cluster {{ $cluster }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-{{ $cluster }}
  namespace: argo
  labels:
    initial: "yes"
    cluster: {{ $cluster }}
    app: traefik
spec:
  project: {{ $.Values.project }}
  source:
    repoURL: {{ $.Values.repoURL }}
    targetRevision: HEAD
    path: traefik
  destination:
    name: {{ $cluster }}
    namespace: traefik
  syncOptions:
  - Validate=true
  - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-{{ $cluster }}
  namespace: argo
  labels:
    initial: "yes"
    cluster: {{ $cluster }}
    app: sealed-secrets
spec:
  project: {{ $.Values.project }}
  source:
    repoURL: {{ $.Values.repoURL }}
    targetRevision: HEAD
    path: sealed-secrets
  destination:
    name: {{ $cluster }}
    namespace: kube-system
  syncOptions:
  - Validate=true
  - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-{{ $cluster }}
  namespace: argo
  labels:
    initial: "yes"
    cluster: {{ $cluster }}
    app: nginx
spec:
  project: {{ $.Values.project }}
  source:
    repoURL: {{ $.Values.repoURL }}
    targetRevision: HEAD
    path: nginx
  destination:
    name: {{ $cluster }}
    namespace: default
  syncOptions:
  - Validate=true
  - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server-{{ . }}
  namespace: argo
  labels:
    initial: "yes"
    cluster: {{ $cluster }}
    app: metrics-server
spec:
  project: {{ $.Values.project }}
  source:
    repoURL: {{ $.Values.repoURL }}
    targetRevision: HEAD
    path: metrics-server
  destination:
    name: {{ $cluster }}
    namespace: kube-system
  syncOptions:
  - Validate=true
  - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dashboard-{{ . }}
  namespace: argo
  labels:
    cluster: {{ $cluster }}
    app: dashboard
spec:
  project: {{ $.Values.project }}
  source:
    repoURL: {{ $.Values.repoURL }}
    targetRevision: HEAD
    path: dashboard
  destination:
    name: {{ $cluster }}
    namespace: kubernetes-dashboard
  syncOptions:
  - Validate=true
  - CreateNamespace=true
---
{{ range $n, $i := $.Values.kadApps }}
# kad {{ $cluster }}-{{ $i }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kad-v{{ $i }}-{{ $cluster }}
  namespace: argo
  labels:
    cluster: {{ $cluster }}
    app: kad
    kad/version: "{{ $i }}"
spec:
  project: {{ $.Values.project }}
  source:
    repoURL: {{ $.Values.repoURL }}
    targetRevision: HEAD
    path: app_v{{ $i }}
  destination:
    name: {{ $cluster }}
    namespace: kad
  syncOptions:
  - Validate=true
  - CreateNamespace=true
---
{{ end }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kad-ingress-{{ . }}
  namespace: argo
  labels:
    cluster: {{ $cluster }}
    app: kad-ingress
spec:
  project: {{ $.Values.project }}
  source:
    repoURL: {{ $.Values.repoURL }}
    targetRevision: HEAD
    path: ingress
  destination:
    name: {{ $cluster }}
    namespace: kad
  syncOptions:
  - Validate=true
  - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-{{ $cluster }}
  namespace: argo
  labels:
    cluster: {{ $cluster }}
    app: prometheus
spec:
  project: {{ $.Values.project }}
  source:
    repoURL: {{ $.Values.repoURL }}
    targetRevision: HEAD
    path: prometheus
  destination:
    name: {{ $cluster }}
    namespace: prometheus
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-{{ $cluster }}
  namespace: argo
  labels:
    cluster: {{ $cluster }}
    app: minio
spec:
  project: {{ $.Values.project }}
  source:
    repoURL: {{ $.Values.repoURL }}
    targetRevision: HEAD
    path: minio
  destination:
    name: {{ $cluster }}
    namespace: minio
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-{{ $cluster }}
  namespace: argo
  labels:
    cluster: {{ $cluster }}
    app: loki
spec:
  project: {{ $.Values.project }}
  source:
    repoURL: {{ $.Values.repoURL }}
    targetRevision: HEAD
    path: loki
  destination:
    name: {{ $cluster }}
    namespace: loki
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: limits-{{ $cluster }}
  namespace: argo
  labels:
    cluster: {{ $cluster }}
    app: limits
spec:
  project: {{ $.Values.project }}
  source:
    repoURL: {{ $.Values.repoURL }}
    targetRevision: HEAD
    path: limits
  destination:
    name: {{ $cluster }}
    namespace: kad
  syncOptions:
  - Validate=true
  - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: policy-{{ $cluster }}
  namespace: argo
  labels:
    cluster: {{ $cluster }}
    app: policy
spec:
  project: {{ $.Values.project }}
  source:
    repoURL: {{ $.Values.repoURL }}
    targetRevision: HEAD
    path: policy
  destination:
    name: {{ $cluster }}
    namespace: kad
{{- end }}
