{{- range .Values.clusters }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-{{ . }}
  namespace: argocd
  labels:
    initial: "yes"
    cluster: "{{ . }}"
spec:
  project: {{ $.Values.project }}
  source:
    repoURL: {{ $.Values.repoURL }}
    targetRevision: HEAD
    path: traefik
  destination:
    name: {{ . }}
    namespace: traefik
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-{{ . }}
  namespace: argocd
  labels:
    initial: "yes"
    cluster: "{{ . }}"
spec:
  project: {{ $.Values.project }}
  source:
    repoURL: {{ $.Values.repoURL }}
    targetRevision: HEAD
    path: nginx
  destination:
    name: {{ . }}
    namespace: default
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server-{{ . }}
  namespace: argocd
  labels:
    initial: "yes"
    cluster: "{{ . }}"
spec:
  project: {{ $.Values.project }}
  source:
    repoURL: {{ $.Values.repoURL }}
    targetRevision: HEAD
    path: metrics-server
  destination:
    name: {{ . }}
    namespace: kube-system
{{- end }}
