apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argo
  labels:
    initial: "yes"
spec:
  project: {{ .Values.project }}
  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: HEAD
    path: argo/cd
  destination:
    server: {{ .Values.masterServer }}
    namespace: argo
